apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana-0001
  labels:
    release: grafana1
spec :
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /pv1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana-0001
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: slow
  selector:
    matchLabels:
      release: "grafana1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prome-0001
  labels:
    release: prome1
spec :
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /pv2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prome-0001
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: slow
  selector:
    matchLabels:
      release: "prome1"
