apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp
        image: registry.cn-shanghai.aliyuncs.com/public-namespace/myapp:v1
        ports:
        - containerPort: 80
